spring:
  application:
    name: CONFIG-DEV
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
